import type { BriefsResponse } from "./types";

// Demo data used when the live backend is unreachable. Mirrors the exact API
// shapes and the scenarios in docs/ARCHITECTURE.md (Flows A & B).

export const fixtureBriefs: BriefsResponse = {
  briefs: [
    {
      brief_id: "brief-eq101-seal",
      recipient_user_id: "dev-user",
      priority: "high",
      trigger_event_type: "work_order_created",
      headline: "EQ-101 — mechanical seal, 4th failure in 8 years",
      body: "The previous failure (14 months ago) was preceded by the same thermal-cycling pattern currently visible in telemetry. The OEM revised the seal specification 18 months ago — confirm you have the current variant (P/N MS-4471-B, not MS-4470-A) before you begin. A field technician noted unusual vibration before the last failure; this was never formally investigated.",
      action_items: [
        "Confirm current seal variant P/N MS-4471-B before install",
        "Check bearing housing clearances during this repair",
        "Attach seal replacement documentation for the upcoming audit",
      ],
      warnings: ["Audit requires seal replacement documentation before 2026-07-15"],
      sources: [
        {
          document_id: "DOC-P101-FAILURE-HIST",
          document_type: "maintenance_record",
          title: "EQ-101 Failure History Report",
          authority_level: 2,
          relevant_excerpt:
            "Four mechanical-seal failures recorded 2018–2026; three preceded by thermal cycling beyond the OEM envelope.",
          vault_url: "https://vault.kairos.local/DOC-P101-FAILURE-HIST",
          is_quarantine: false,
        },
        {
          document_id: "OEM-BULL-MS44-r3",
          document_type: "oem_manual",
          title: "Seal Series MS-44 Service Bulletin r3",
          authority_level: 3,
          relevant_excerpt: "Supersedes MS-4470-A with MS-4471-B effective 2024-11.",
          vault_url: "https://vault.kairos.local/OEM-BULL-MS44-r3",
          is_quarantine: false,
        },
        {
          document_id: "QN-EQ101-VIB-0142",
          document_type: "field_observation",
          title: "Field note — unusual vibration on EQ-101",
          authority_level: 5,
          relevant_excerpt: "Operator reported abnormal vibration ~2 weeks before the last seal failure.",
          vault_url: null,
          is_quarantine: true,
        },
      ],
      requires_countersignature: false,
      delivery_frozen: false,
      delivered_at: "2026-07-03T13:58:00Z",
    },
    {
      brief_id: "brief-v247-ptw",
      recipient_user_id: "dev-user",
      priority: "critical",
      trigger_event_type: "ptw_generated",
      headline: "PTW — isolation of V-247, Production Line 3 / Section 2",
      body: "Double-block-and-bleed isolation for valve replacement. Primary isolation XV-203 is approaching its 18-month inspection interval (last inspected 14 months ago). Local gauge bypass PG-18 has an unresolved field deviation: an operator flagged it may not be seating fully 3 weeks ago. Verify PG-18 physically before proceeding.",
      action_items: [
        "Isolate at XV-203 (primary) and XV-204 (secondary bleed)",
        "Physically verify PG-18 seating before energizing the work",
        "Countersignature from Shift Lead required before PTW issue",
      ],
      warnings: [
        "PG-18 has an unverified deviation flag — treat as suspect",
        "XV-203 inspection due in 4 months",
      ],
      sources: [
        {
          document_id: "TOPO-PL3-S2",
          document_type: "drawing_topology",
          title: "P&ID topology — Line 3, Section 2 isolation boundary",
          authority_level: 3,
          relevant_excerpt: "Isolation boundary: XV-203 (primary), XV-204 (bleed), PG-18 (gauge bypass).",
          vault_url: "https://vault.kairos.local/TOPO-PL3-S2",
          is_quarantine: false,
        },
        {
          document_id: "QN-PG18-SEAT-0210",
          document_type: "deviation_flag",
          title: "Deviation — PG-18 may not seat fully",
          authority_level: 5,
          relevant_excerpt: "Field flag raised 2026-06-12; not yet reviewed by engineering.",
          vault_url: null,
          is_quarantine: true,
        },
      ],
      requires_countersignature: true,
      delivery_frozen: false,
      delivered_at: "2026-07-03T13:40:00Z",
    },
    {
      brief_id: "brief-hx301-recurring",
      recipient_user_id: "dev-user",
      priority: "high",
      trigger_event_type: "recurring_failure_detected",
      headline: "HX-301 — tube fouling recurring: 3 work orders in 90 days",
      body: "Three fouling-related work orders opened on HX-301 in the last 90 days. The pattern matches a known feed-water quality issue at two sister exchangers. Consider a root-cause review rather than another clean-in-place.",
      action_items: [
        "Review feed-water quality trend before scheduling another CIP",
        "Cross-reference HX-302 and HX-305 fouling history",
      ],
      warnings: [],
      sources: [
        {
          document_id: "DOC-HX3-FOULING",
          document_type: "maintenance_record",
          title: "HX-3xx fouling trend analysis",
          authority_level: 2,
          relevant_excerpt: "Recurring fouling correlated with feed-water hardness excursions.",
          vault_url: "https://vault.kairos.local/DOC-HX3-FOULING",
          is_quarantine: false,
        },
      ],
      requires_countersignature: false,
      delivery_frozen: false,
      delivered_at: "2026-07-03T12:20:00Z",
    },
    {
      brief_id: "brief-shift-handover",
      recipient_user_id: "dev-user",
      priority: "medium",
      trigger_event_type: "shift_handover",
      headline: "Shift handover — 3 open work orders, 1 active PTW, 2 items pending review",
      body: "Incoming shift context: EQ-101 and HX-301 have open work orders; an active PTW on Line 3 expires at 18:00; two quarantine items from the outgoing shift await engineering review.",
      action_items: ["Review the active PTW expiry on Line 3", "Triage 2 pending quarantine items"],
      warnings: ["Active PTW on Line 3 expires 18:00"],
      sources: [
        {
          document_id: "SHIFT-LOG-2026-07-03-A",
          document_type: "shift_log",
          title: "Shift A closeout log",
          authority_level: 4,
          relevant_excerpt: "Open WOs: EQ-101, HX-301. Active PTW: Line 3. Pending review: 2.",
          vault_url: "https://vault.kairos.local/SHIFT-LOG-2026-07-03-A",
          is_quarantine: false,
        },
      ],
      requires_countersignature: false,
      delivery_frozen: false,
      delivered_at: "2026-07-03T11:05:00Z",
    },
  ],
  total_pending: 4,
  suppressed_count: 0,
  governor_state: { push_count_last_hour: 4, ceiling: 6, state: "normal" },
  next_delivery_allowed_at: null,
};
